### ISSUE TITLE
Incorporate this dynamics package

### ISSUE THREAD

**Issue by leotrs** [xgi-org/xgi#21]
https://github.com/arnaudon/simplicial-kuramoto

**Comment by maximelucas** [comment]
Happening in #251

**Comment by arnaudon** [comment]
Hello guys, I'm thinking if it would be better to incorporate it inside XGI, or use XGI in it, and let it be a separate Kuramoto package? I don't have a strong opinion, just to maybe overload this one with too much 'extra' stuff, and leave xgi as more of a 'core' package?

**Comment by lordgrilo** [comment]
We have discussed this a few times and didn't really come to a strong conclusion. So far however the consensus would be that it's better to keep the core structural xgi part separate from the dynamics (since there are many possible parts and it might be hard to test/validate/keep updated them all). We were considering having a separate repo e.g. xgi-dynamics that incorporates all the proposals for dynamical models

**Comment by arnaudon** [comment]
oke doke, let see later then. For now I have implemented a little converter from xgi to my internal variable names here: https://github.com/arnaudon/simplicial-kuramoto/pull/8 so we can reuse my package as is, while dealing with simplicial complex via xgi.

**Comment by leotrs** [comment]
As per recent conversations, I think it's safe to say that the current position is the following. We want to highlight packages that use XGI without the need to incorporate them to XGI fully. Perhaps this is a prime candidate to start a list of recommended/official/related packages in the main README of this repository.

**Comment by maximelucas** [comment]
It's now on the "Projects using XGI page".
