### ISSUE TITLE
draw_hypergraph_hull  not working

### ISSUE THREAD

**Issue by johannagehlen** [xgi-org/xgi#336]
module 'xgi' has no attribute 'draw_hypergraph_hull'. 
I tried to follow the tutorial 7, but I am getting this error.

**Comment by leotrs** [comment]
Hi @johannagehlen ! Thanks for reporting this. Would you please be able to tell us what version of XGI you are using?

**Comment by leotrs** [comment]
Thanks! I just checked and the problem is the following. The addition of Tutorial 7 and draw_hypergraph_hull has not yet been released to the pypi version of the library. I would recommend waiting until the next version to be able to use it. However, if you really needed it, you could try installing XGI by cloning the main branch of this repository. Of course in that way you'd be using the latest and unstable of the library, so be warned!

**Comment by johannagehlen** [comment]
Oh I see, do you know approximately when the next version would be released? Thank you :)

**Comment by leotrs** [comment]
That's a question for @nwlandry

**Comment by nwlandry** [comment]
Hi @johannagehlen! Thanks for raising this issue! I am working on releasing a new version right now (should be done in the next hour) and I will update this issue when it's done.

**Comment by johannagehlen** [comment]
awesome thank you sm!!

**Comment by nwlandry** [comment]
Okay, should be updated now. If you run `pip install --upgrade xgi` it should install version 0.5.7 and notebook 7 should work. Thanks for your patience :)

**Comment by nwlandry** [comment]
If you could let me know if it works, that would be great! And if not, we can troubleshoot some more.

**Comment by johannagehlen** [comment]
great it works now, thanks guys for the fast response!

**Comment by leotrs** [comment]
Please don't hesitate to report any other issues!

**Comment by leotrs** [comment]
Jinx
