### ISSUE TITLE
Set the `nan` color when drawing

### ISSUE THREAD

**Issue by nwlandry** [xgi-org/xgi#448]
When coloring, for example, a node face using a `NodeStat`, the `draw` function makes the node transparent if the data is nan. It might be nice to be able to specify this if you wanted to.

**Comment by maximelucas** [comment]
Good idea. I think this can be solved naturally in #441 because [`plt.scatter`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html) allows to deal with non-finite values: 


<img width="620" alt="Screenshot 2023-08-14 at 12 12 08" src="https://github.com/xgi-org/xgi/assets/7493360/4ef0eb40-ae2e-4dc3-9cd2-6b0fa6efcd07">

The color used can then be set in the cmap used. 

Do you think this would be enough or you'd prefer some vanilla way to access that functionality more easily?

**Comment by maximelucas** [comment]
#441 solved this for drawing nodes. Still needs fixing for drawing hyperedges I guess?

**Comment by maximelucas** [comment]
#456 solved this for drawing hyperedges. Still could be implemented for `draw_multilayer` and `draw_dihypergraph`. Closing for now.
